# Generated by Django 4.1.7 on 2023-04-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ad_type',
            field=models.CharField(choices=[('', 'Search Engine Optimization '), ('', 'Social Media Marketing'), ('', 'Email Marketing'), ('', 'Pay-Per-Click Advertising'), ('', 'Data Analytics')], default='Outdoor Advertising', max_length=128),
        ),
    ]
