# Generated by Django 4.1.7 on 2023-04-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_alter_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ad_type',
            field=models.CharField(max_length=4),
        ),
    ]
