# Generated by Django 4.1.7 on 2023-04-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0007_contact_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ad_type',
            field=models.CharField(max_length=4),
        ),
    ]
