# Generated by Django 4.1.7 on 2023-04-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_alter_contact_ad_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ad_type',
            field=models.CharField(choices=[('outdoor_advertising', 'Outdoor Advertising'), ('agent_partnership', 'Agent Partnership')], default='Outdoor Advertising', max_length=128),
        ),
    ]
