# Generated by Django 4.1.7 on 2023-05-01 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_alter_contact_ad_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ad_type',
        ),
    ]
